USE cfb_schema;
CREATE TABLE ESPN_ID (
    TeamName VARCHAR(50) PRIMARY KEY,
    ESPN_ID INT,
    ESPN_Nickname VARCHAR(50)
);
INSERT INTO ESPN_ID (TeamName, ESPN_ID, ESPN_Nickname) VALUES
 ('Air Force', 2005, 'Air Force'),
 ('Akron', 2006, 'Akron'),
 ('Alabama', 333, 'Alabama'),
 ('App State', 2026, 'App State'),
 ('Arizona', 12, 'Arizona'),
 ('Arizona State', 9, 'Arizona St'),
 ('Arkansas', 8, 'Arkansas'),
 ('Arkansas State', 2032, 'Arkansas St'),
 ('Army', 349, 'Army'),
 ('Auburn', 2, 'Auburn'),
 ('Ball State', 2050, 'Ball State'),
 ('Baylor', 239, 'Baylor'),
 ('Boise State', 68, 'Boise St'),
 ('Boston College', 103, 'Boston College'),
 ('Bowling Green', 189, 'Bowling Green'),
 ('Buffalo', 2084, 'Buffalo'),
 ('BYU', 252, 'BYU'),
 ('California', 25, 'California'),
 ('Central Michigan', 2117, 'C Michigan'),
 ('Charlotte', 2429, 'Charlotte'),
 ('Cincinnati', 2132, 'Cincinnati'),
 ('Clemson', 228, 'Clemson'),
 ('Coastal Carolina', 324, 'Coastal Car'),
 ('Colorado', 38, 'Colorado'),
 ('Colorado State', 36, 'Colorado St'),
 ('Duke', 150, 'Duke'),
 ('East Carolina', 151, 'East Carolina'),
 ('Eastern Michigan', 2199, 'E Michigan'),
 ('Florida', 57, 'Florida'),
 ('Florida Atlantic', 2226, 'FAU'),
 ('Florida International', 2229, 'FIU'),
 ('Florida State', 52, 'Florida St'),
 ('Fresno State', 278, 'Fresno St'),
 ('Georgia', 61, 'Georgia'),
 ('Georgia Southern', 290, 'GA Southern'),
 ('Georgia State', 2247, 'Georgia St'),
 ('Georgia Tech', 59, 'Georgia Tech'),
 ('Hawaii', 62, 'Hawaii'),
 ('Houston', 248, 'Houston'),
 ('Illinois', 356, 'Illinois'),
 ('Indiana', 84, 'Indiana'),
 ('Iowa', 2294, 'Iowa'),
 ('Iowa State', 66, 'Iowa State'),
 ('Jacksonville State', 55, 'Jax State'),
 ('James Madison', 256, 'James Madison'),
 ('Kansas', 2305, 'Kansas'),
 ('Kansas State', 2306, 'Kansas St'),
 ('Kennesaw State', 338, 'Kennesaw St'),
 ('Kent State', 2309, 'Kent State'),
 ('Kentucky', 96, 'Kentucky'),
 ('Liberty', 2335, 'Liberty'),
 ('Louisiana', 309, 'Louisiana'),
 ('Louisiana Tech', 2348, 'Louisiana Tech'),
 ('Louisville', 97, 'Louisville'),
 ('LSU', 99, 'LSU'),
 ('Marshall', 276, 'Marshall'),
 ('Maryland', 120, 'Maryland'),
 ('Massachusetts', 113, 'UMass'),
 ('Memphis', 235, 'Memphis'),
 ('Miami', 2390, 'Miami'),
 ('Miami (OH)', 193, 'Miami OH'),
 ('Michigan', 130, 'Michigan'),
 ('Michigan State', 127, 'Michigan St'),
 ('Middle Tennessee', 2393, 'MTSU'),
 ('Minnesota', 135, 'Minnesota'),
 ('Mississippi State', 344, 'Mississippi St'),
 ('Missouri', 142, 'Missouri'),
 ('Navy', 2426, 'Navy'),
 ('NC State', 152, 'NC State'),
 ('Nebraska', 158, 'Nebraska'),
 ('Nevada', 2440, 'Nevada'),
 ('New Mexico', 167, 'New Mexico'),
 ('New Mexico State', 166, 'New Mexico St'),
 ('North Carolina', 153, 'North Carolina'),
 ('Northern Illinois', 2459, 'N Illinois'),
 ('North Texas', 249, 'North Texas'),
 ('Northwestern', 77, 'Northwestern'),
 ('Notre Dame', 87, 'Notre Dame'),
 ('Ohio', 195, 'Ohio'),
 ('Ohio State', 194, 'Ohio State'),
 ('Oklahoma', 201, 'Oklahoma'),
 ('Oklahoma State', 197, 'Oklahoma St'),
 ('Old Dominion', 295, 'Old Dominion'),
 ('Ole Miss', 145, 'Ole Miss'),
 ('Oregon', 2483, 'Oregon'),
 ('Oregon State', 204, 'Oregon St'),
 ('Penn State', 213, 'Penn State'),
 ('Pittsburgh', 221, 'Pitt'),
 ('Purdue', 2509, 'Purdue'),
 ('Rice', 242, 'Rice'),
 ('Rutgers', 164, 'Rutgers'),
 ('Sam Houston', 2534, 'Sam Houston'),
 ('San Diego State', 21, 'San Diego St'),
 ('San José State', 23, 'San José St'),
 ('SMU', 2567, 'SMU'),
 ('South Alabama', 6, 'South Alabama'),
 ('South Carolina', 2579, 'South Carolina'),
 ('Southern Miss', 2572, 'Southern Miss'),
 ('South Florida', 58, 'South Florida'),
 ('Stanford', 24, 'Stanford'),
 ('Syracuse', 183, 'Syracuse'),
 ('TCU', 2628, 'TCU'),
 ('Temple', 218, 'Temple'),
 ('Tennessee', 2633, 'Tennessee'),
 ('Texas', 251, 'Texas'),
 ('Texas A&M', 245, 'Texas A&M'),
 ('Texas State', 326, 'Texas St'),
 ('Texas Tech', 2641, 'Texas Tech'),
 ('Toledo', 2649, 'Toledo'),
 ('Troy', 2653, 'Troy'),
 ('Tulane', 2655, 'Tulane'),
 ('Tulsa', 202, 'Tulsa'),
 ('UAB', 5, 'UAB'),
 ('UCF', 2116, 'UCF'),
 ('UCLA', 26, 'UCLA'),
 ('UConn', 41, 'UConn'),
 ('UL Monroe', 2433, 'UL Monroe'),
 ('UNLV', 2439, 'UNLV'),
 ('USC', 30, 'USC'),
 ('Utah', 254, 'Utah'),
 ('Utah State', 328, 'Utah State'),
 ('UTEP', 2638, 'UTEP'),
 ('UTSA', 2636, 'UTSA'),
 ('Vanderbilt', 238, 'Vanderbilt'),
 ('Virginia', 258, 'Virginia'),
 ('Virginia Tech', 259, 'Virginia Tech'),
 ('Wake Forest', 154, 'Wake Forest'),
 ('Washington', 264, 'Washington'),
 ('Washington State', 265, 'Washington St'),
 ('Western Kentucky', 98, 'Western KY'),
 ('Western Michigan', 2711, 'W Michigan'),
 ('West Virginia', 277, 'West Virginia'),
 ('Wisconsin', 275, 'Wisconsin'),
 ('Wyoming', 2751, 'Wyoming'),
 ('Delaware', 48, 'Delaware'),
 ('Missouri State', 2623, 'Missouri St');