USE cfb_schema;
CREATE TABLE HFA (
    TeamName VARCHAR(50) PRIMARY KEY,
    HFA DECIMAL(10,4)
);
INSERT INTO HFA (TeamName, HFA) VALUES
 ('Notre Dame', 5.6),  
('Oklahoma State', 2.2),  
('Kansas State', 7.7),  
('Baylor', 2),  
('Iowa State', 3.6),  
('Texas Tech', 1.5),  
('Kansas', 4.3),  
('TCU', 2.5),  
('West Virginia', 3.1),  
('Massachusetts', -1.5),  
('South Florida', 2.2),  
('East Carolina', 5.6),  
('Tulsa', -2.1),  
('Temple', 4),  
('Memphis', 2.7),  
('Navy', 2.5),  
('Tulane', 5.4),  
('Western Kentucky', 4),  
('Florida International', -0.5),  
('Louisiana Tech', 2.8),  
('Middle Tennessee', 3.9),  
('UTEP', 1.5),  
('Oregon State', 8.3),  
('Washington State', 3.7),  
('James Madison', 10),  
('Marshall', -0.1),  
('Georgia Southern', 5.2),  
('Old Dominion', 4.9),  
('Coastal Carolina', 0.8),  
('App State', 2.8),  
('Georgia State', -2.4),  
('South Alabama', 6.1),  
('Louisiana', 5.5),  
('Texas State', 5.2),  
('Arkansas State', 3.2),  
('UL Monroe', 7.3),  
('Southern Miss', 0.2),  
('Troy', 2),  
('UConn', 5.3),  
('BYU', 3.3),  
('Cincinnati', 2.5),  
('Houston', 0.6),  
('UCF', 4.3),  
('UAB', 0.5),  
('Florida Atlantic', 0.9),  
('Charlotte', -4.3),  
('North Texas', 4.6),  
('Rice', 2.7),  
('UTSA', 4.8),  
('Jacksonville State', 4.8),  
('Liberty', -0.6),  
('New Mexico State', 6.4),  
('Sam Houston', -1.5),  
('Army', 2.4),  
('Stanford', -1.7),  
('California', 2.7),  
('Florida State', 0.9),  
('Georgia Tech', -1.8),  
('Louisville', 8.7),  
('Boston College', -0.3),  
('Duke', 4.9),  
('NC State', 4),  
('North Carolina', 0.3),  
('Wake Forest', 0.9),  
('Syracuse', 3.6),  
('Pittsburgh', 3.4),  
('Clemson', 0.8),  
('Virginia', -0.6),  
('Virginia Tech', 3.2),  
('Miami', -2.7),  
('SMU', 7.9),  
('Arizona State', 0.2),  
('Arizona', 1.7),  
('Colorado', 3.3),  
('Utah', 6.2),  
('UCLA', 0.6),  
('USC', 0.1),  
('Northwestern', 0),  
('Indiana', 1.8),  
('Iowa', 3.2),  
('Maryland', 1.2),  
('Michigan State', -0.1),  
('Michigan', 3),  
('Minnesota', 3.9),  
('Nebraska', 1.6),  
('Rutgers', -0.1),  
('Ohio State', 5.3),  
('Penn State', 2.7),  
('Washington', 3.6),  
('Wisconsin', -0.1),  
('Illinois', 4),  
('Oregon', 4),  
('Purdue', -0.2),  
('Kennesaw State', -0.3),  
('Bowling Green', -1.1),  
('Miami (OH)', 2.1),  
('Ohio', 3.3),  
('Akron', -2),  
('Ball State', 4.6),  
('Buffalo', 2),  
('Central Michigan', 2.5),  
('Eastern Michigan', -0.9),  
('Kent State', -0.7),  
('Northern Illinois', -2.3),  
('Toledo', 2.7),  
('Western Michigan', 1.6),  
('San Diego State', 0.1),  
('San José State', 1.1),  
('Colorado State', -0.6),  
('Hawaii', 5),  
('Boise State', 4.6),  
('New Mexico', -0.7),  
('Fresno State', 2.5),  
('Utah State', 2.8),  
('Air Force', 2.9),  
('UNLV', 5.1),  
('Nevada', 0.9),  
('Wyoming', 3.5),  
('Auburn', 1.7),  
('Arkansas', -0.7),  
('Florida', 2.7),  
('Georgia', 1.2),  
('Kentucky', 2.2),  
('LSU', 5.3),  
('Missouri', 1.9),  
('Ole Miss', 4.2),  
('Oklahoma', 2.4),  
('Vanderbilt', 0),  
('Texas A&M', 4.1),  
('Texas', 4.5),  
('Alabama', 2.9),  
('Mississippi State', 0.9),  
('South Carolina', 4.3),  
('Tennessee', 7);